"""Cloudflare: tunnel config generation, service control and DNS records.

Safety rule: a DNS record is only ever created if the name is free, and only
ever deleted if it points at *this* server's tunnel. Records belonging to other
tunnels or services are never touched.
"""
import base64
import json
import os
import subprocess
import tempfile
import urllib.error
import urllib.request

from . import state

CF_DIR = "/etc/cloudflared"
API = "https://api.cloudflare.com/client/v4"
METRICS_BASE_PORT = 20241


class CFError(Exception):
    pass


def read_cert(path):
    with open(path) as f:
        body = "".join(l for l in f.read().splitlines() if not l.startswith("-----"))
    return json.loads(base64.b64decode(body))


def _api(token, method, path, body=None):
    req = urllib.request.Request(
        API + path,
        method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Authorization": "Bearer " + token, "Content-Type": "application/json"},
    )
    try:
        res = json.loads(urllib.request.urlopen(req, timeout=20).read())
    except urllib.error.HTTPError as e:
        res = json.loads(e.read() or b"{}")
    if not res.get("success"):
        msgs = "; ".join(e.get("message", "") for e in res.get("errors", [])) or "unknown error"
        raise CFError("Cloudflare API: " + msgs)
    return res["result"]


def _zone_ctx(data, hostname):
    zone = state.zone_for(data, hostname)
    if not zone:
        raise CFError("الدومين %s لا يتبع أي حساب Cloudflare مربوط بهذا الخادم" % hostname)
    z = data["zones"][zone]
    cert = read_cert(z["cert"])
    acct = data["accounts"][z["account"]]
    return z["account"], acct, cert


def tunnel_target(acct):
    return "%s.cfargotunnel.com" % acct["tunnel_id"]


def dns_lookup(data, hostname):
    """Return (status, record). status: free | ours | foreign."""
    _, acct, cert = _zone_ctx(data, hostname)
    recs = _api(cert["apiToken"], "GET", "/zones/%s/dns_records?name=%s" % (cert["zoneID"], hostname))
    if not recs:
        return "free", None
    for r in recs:
        if r["type"] == "CNAME" and r["content"] == tunnel_target(acct):
            return "ours", r
    return "foreign", recs[0]


def dns_create(data, hostname):
    status, rec = dns_lookup(data, hostname)
    if status == "ours":
        return
    if status == "foreign":
        raise CFError(
            "الاسم %s مستخدم مسبقاً (%s ← %s). لن ألمسه حتى لا يتعطل موقع آخر."
            % (hostname, rec["type"], rec["content"])
        )
    _, acct, cert = _zone_ctx(data, hostname)
    _api(cert["apiToken"], "POST", "/zones/%s/dns_records" % cert["zoneID"], {
        "type": "CNAME", "name": hostname, "content": tunnel_target(acct),
        "proxied": True, "comment": "old-home manager",
    })


def dns_delete(data, hostname):
    status, rec = dns_lookup(data, hostname)
    if status != "ours":
        return False
    _, _, cert = _zone_ctx(data, hostname)
    _api(cert["apiToken"], "DELETE", "/zones/%s/dns_records/%s" % (cert["zoneID"], rec["id"]))
    return True


# ---------- tunnel config + service ----------

def account_routes(data, account):
    return [r for r in data["routes"] if data["zones"].get(state.zone_for(data, r["hostname"]) or "", {}).get("account") == account]


def render_config(data, account):
    acct = data["accounts"][account]
    d = os.path.join(CF_DIR, account)
    lines = [
        "# Generated by old-home manager — edit via the manager, not by hand.",
        "tunnel: %s" % acct["tunnel_id"],
        "credentials-file: %s" % os.path.join(d, acct["tunnel_name"] + ".json"),
        "origincert: %s" % acct["cert"],
        "metrics: 127.0.0.1:%d" % acct["metrics_port"],
        "",
        "ingress:",
    ]
    for r in account_routes(data, account):
        lines.append("  # %s" % (r.get("label") or r.get("kind", "site")))
        lines.append("  - hostname: %s" % r["hostname"])
        lines.append("    service: %s" % r["service"])
        if r.get("no_tls_verify"):
            lines.append("    originRequest:")
            lines.append("      noTLSVerify: true")
    lines.append("  - service: http_status:404")
    return "\n".join(lines) + "\n"


def apply_config(data, account):
    """Write config.yml atomically after cloudflared validates it, then restart."""
    text = render_config(data, account)
    path = os.path.join(CF_DIR, account, "config.yml")
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".config.", suffix=".yml")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    v = subprocess.run(["cloudflared", "tunnel", "--config", tmp, "ingress", "validate"],
                       capture_output=True, text=True)
    if v.returncode != 0:
        os.unlink(tmp)
        raise CFError("إعداد التونل غير صالح: " + (v.stderr or v.stdout).strip())
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)
    restart(account)


def restart(account):
    subprocess.run(["systemctl", "restart", "cloudflared@%s" % account], check=True)


def tunnel_status(data, account):
    acct = data["accounts"][account]
    active = subprocess.run(["systemctl", "is-active", "cloudflared@%s" % account],
                            capture_output=True, text=True).stdout.strip()
    conns = 0
    try:
        r = urllib.request.urlopen("http://127.0.0.1:%d/ready" % acct["metrics_port"], timeout=3)
        conns = json.loads(r.read()).get("readyConnections", 0)
    except Exception:
        pass
    return {"service": active, "connections": conns}
