"""Host health: CPU / memory / disk / temperature / services, logs, nginx real-IP."""
import glob
import os
import shutil
import socket
import subprocess
import time

NGINX = "/www/server/nginx/sbin/nginx"
REALIP_CONF = "/www/server/panel/vhost/nginx/0.cloudflare_realip.conf"
REALIP_TEXT = """# Generated by old-home manager: trust cloudflared (localhost) and use the
# visitor IP that Cloudflare passes in CF-Connecting-IP.
set_real_ip_from 127.0.0.1;
set_real_ip_from ::1;
real_ip_header CF-Connecting-IP;
"""


def _cpu_times():
    with open("/proc/stat") as f:
        parts = [int(x) for x in f.readline().split()[1:]]
    idle = parts[3] + parts[4]
    return idle, sum(parts)


def stats():
    i1, t1 = _cpu_times()
    time.sleep(0.25)
    i2, t2 = _cpu_times()
    cpu = 100.0 * (1 - (i2 - i1) / max(t2 - t1, 1))

    mem = {}
    with open("/proc/meminfo") as f:
        for line in f:
            k, v = line.split(":")
            mem[k] = int(v.split()[0]) * 1024
    du = shutil.disk_usage("/")

    temps = []
    for z in glob.glob("/sys/class/thermal/thermal_zone*/temp"):
        try:
            temps.append(int(open(z).read()) / 1000)
        except (OSError, ValueError):
            pass
    for z in glob.glob("/sys/class/hwmon/hwmon*/temp*_input"):
        try:
            temps.append(int(open(z).read()) / 1000)
        except (OSError, ValueError):
            pass

    with open("/proc/uptime") as f:
        uptime = float(f.read().split()[0])

    return {
        "hostname": socket.gethostname(),
        "cpu": round(cpu, 1),
        "cores": os.cpu_count(),
        "load": os.getloadavg(),
        "mem_total": mem["MemTotal"], "mem_used": mem["MemTotal"] - mem["MemAvailable"],
        "disk_total": du.total, "disk_used": du.used,
        "temp": round(max(temps), 1) if temps else None,
        "uptime": int(uptime),
    }


def _port_open(port):
    with socket.socket() as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def panel_port():
    try:
        return int(open("/www/server/panel/data/port.pl").read().strip())
    except (OSError, ValueError):
        return 0


def panel_admin_path():
    try:
        return open("/www/server/panel/data/admin_path.pl").read().strip()
    except OSError:
        return ""


def services():
    out = [
        {"id": "aapanel", "name": "aaPanel" if panel_port() else "aaPanel (غير مثبّت)",
         "ok": bool(panel_port()) and _port_open(panel_port())},
        {"id": "nginx", "name": "Nginx", "ok": _port_open(80)},
        {"id": "mysqld", "name": "MySQL / MariaDB", "ok": _port_open(3306)},
        {"id": "ssh", "name": "SSH", "ok": _port_open(22)},
    ]
    if os.path.exists("/etc/fail2ban/jail.d/oldhome-sshd.local"):
        f2b = subprocess.run(["systemctl", "is-active", "--quiet", "fail2ban"]).returncode == 0
        out.append({"id": "fail2ban", "name": "fail2ban (حماية SSH)", "ok": f2b})
    for d in sorted(glob.glob("/www/server/php/[0-9][0-9]")):
        v = os.path.basename(d)
        out.append({"id": "php-fpm-" + v, "name": "PHP %s.%s" % (v[0], v[1]),
                    "ok": os.path.exists("/tmp/php-cgi-%s.sock" % v)})
    return out


RESTARTABLE = {
    "fail2ban": ["systemctl", "restart", "fail2ban"],
    "aapanel": ["systemctl", "restart", "btpanel"],
    "nginx": ["/etc/init.d/nginx", "reload"],
    "mysqld": ["/etc/init.d/mysqld", "restart"],
}


def restart_service(sid):
    if sid in RESTARTABLE:
        cmd = RESTARTABLE[sid]
    elif sid.startswith("php-fpm-") and sid[8:].isdigit():
        cmd = ["/etc/init.d/" + sid, "restart"]
    else:
        raise ValueError("unknown service")
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    return r.returncode == 0, (r.stdout + r.stderr)[-2000:]


def site_force_https(hostname):
    """True when aaPanel's "Force HTTPS" is on: port 80 just redirects to 443,
    so a tunnel pointed at :80 would loop forever."""
    try:
        with open("/www/server/panel/vhost/nginx/%s.conf" % hostname) as f:
            return "HTTP_TO_HTTPS_START" in f.read()
    except OSError:
        return False


def site_origin(hostname):
    """Tunnel route settings that work for this site's current SSL setup."""
    if site_force_https(hostname):
        return {"service": "https://localhost:443", "no_tls_verify": True, "origin_server_name": hostname}
    return {"service": "http://localhost:80"}


def site_http_status(hostname):
    """Ask nginx directly (bypasses DNS) whether it serves this host."""
    r = subprocess.run(["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "--max-time", "5",
                        "-A", "Mozilla/5.0 old-home-manager", "-H", "Host: " + hostname,
                        "http://127.0.0.1/"], capture_output=True, text=True)
    return r.stdout.strip() or "000"


# ---------- logs ----------

def log_sources(accounts, sites):
    src = [{"id": "tunnel:" + a, "name": "التونل — " + a} for a in accounts]
    src.append({"id": "nginx", "name": "Nginx — الأخطاء العامة"})
    for s in sites:
        src.append({"id": "site-err:" + s, "name": s + " — الأخطاء"})
        src.append({"id": "site-acc:" + s, "name": s + " — الزيارات"})
    return src


def read_log(source, lines=200):
    lines = max(10, min(int(lines), 2000))
    kind, _, name = source.partition(":")
    if kind == "tunnel" and name.replace("-", "").replace("_", "").isalnum():
        cmd = ["journalctl", "-u", "cloudflared@" + name, "-n", str(lines), "--no-pager", "-o", "short-iso"]
        return subprocess.run(cmd, capture_output=True, text=True).stdout
    if kind == "nginx":
        path = "/www/wwwlogs/nginx_error.log"
    elif kind in ("site-err", "site-acc") and "/" not in name and ".." not in name:
        path = "/www/wwwlogs/%s%s" % (name, ".error.log" if kind == "site-err" else ".log")
    else:
        raise ValueError("unknown log")
    if not os.path.exists(path):
        return "(السجل فارغ أو غير موجود بعد)"
    return subprocess.run(["tail", "-n", str(lines), path], capture_output=True, text=True).stdout


# ---------- nginx real visitor IP ----------

def realip_enabled():
    return os.path.exists(REALIP_CONF)


def set_realip(enable):
    if enable:
        with open(REALIP_CONF, "w") as f:
            f.write(REALIP_TEXT)
    elif os.path.exists(REALIP_CONF):
        os.unlink(REALIP_CONF)
    t = subprocess.run([NGINX, "-t"], capture_output=True, text=True)
    if t.returncode != 0:
        if enable and os.path.exists(REALIP_CONF):
            os.unlink(REALIP_CONF)
        raise RuntimeError(t.stderr.strip())
    subprocess.run(["/etc/init.d/nginx", "reload"], capture_output=True)
